# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# See: https://aquasecurity.github.io/trivy/latest/docs/configuration/filtering/

# Format:
#  - id: <CVE-###>
#    statement: "<Why are we excluding?> <link to CVE where we can we status>"
#    expired_at: <required - YYYY-MM-DD>

vulnerabilities:
  - id: CVE-2026-54515
    statement: "jackson-databind vulnerability. No fix available in 2.21.x yet (Trivy DB lists 2.21.5 which has not been released). https://avd.aquasec.com/nvd/cve-2026-54515"
    expired_at: 2026-07-31
