name: Build and Push Java-Agent Image after CPUtility Test
description: |
  cpUtility Testing
  This action assumes that Repo was checked out and Java was set correctly

inputs:
  aws-region:
    required: true
    description: "AWS Region"
  image_uri_with_tag:
    required: true
    description: "Image URI with Tag"
  image_registry:
    required: true
    description: "Image Registry"
  adot-java-version:
    required: true
    description: "ADOT Java Version"
  snapshot-ecr-role:
    require: true
    description: "IAM Role used for pushing to snapshot ecr"


runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:v0.15.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.snapshot-ecr-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to private staging ecr
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.image_registry }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Build image for testing
      uses: docker/build-push-action@v5
      with:
        push: false
        build-args: "ADOT_JAVA_VERSION=${{ inputs.adot-java-version }}"
        context: .
        platforms: linux/amd64
        tags: ${{ inputs.image_uri_with_tag }}
        load: true

    - name: Test docker image
      shell: bash
      run: .github/scripts/test-adot-javaagent-image.sh "${{ inputs.image_uri_with_tag }}" "${{ inputs.adot-java-version }}"

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: "ADOT_JAVA_VERSION=${{ inputs.adot-java-version }}"
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ inputs.image_uri_with_tag }}