name: "Patch dependencies"
description: |
  Patches direct dependencies of this project leveraging maven local to publish the results.

  This workflow supports patching opentelemetry-java and opentelemetry-java-contrib repositories by executing
  the `patch.sh` script that will try to patch those repositories and after that will optionally test and then publish
  the artifacts to maven local.
  To add a patch you have to add a file in the `.github/patches/` directory with the name of the repository that must
  be patched.
  This action assumes that java was set correctly.
inputs:
  run_tests:
    default: "false"
    required: false
    description: "If the workflow should run tests of the dependencies. Anything different than false will evaluate to true"
  gpg_private_key:
    description: "The gpg key used to sign the artifacts"
    required: false
  gpg_password:
    description: "The gpg key password"
    required: false
runs:
  using: "composite"
  steps:
    - name: set environment variables
      env:
        INPUT_KEY: ${{ inputs.gpg_private_key }}
        INPUT_PASSWORD: ${{ inputs.gpg_password }}
      shell: bash
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        if [[ ! -z "$INPUT_KEY" ]]; then
          {
            echo "GPG_PRIVATE_KEY<<$EOF"
            echo "$INPUT_KEY"
            echo "$EOF"
          } >> "$GITHUB_ENV"
        fi
        if [[ ! -z "$INPUT_PASSWORD" ]]; then
          {
            echo "GPG_PASSWORD<<$EOF"
            echo "$INPUT_PASSWORD"
            echo "$EOF"
          } >> "$GITHUB_ENV"
        fi

    - name: check patches
      run: |
        if [[ -f .github/patches/opentelemetry-java.patch ]]; then
          echo 'patch_otel_java=true' >> $GITHUB_ENV
        fi
        if [[ -f .github/patches/opentelemetry-java-contrib.patch ]]; then
            echo 'patch_otel_java_contrib=true' >> $GITHUB_ENV
        fi
      shell: bash

    - name: Clone and patch repositories
      run: .github/scripts/patch.sh
      if: ${{ env.patch_otel_java == 'true' ||
              env.patch_otel_java_contrib == 'true' }}
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a #4.4.3
     
    - name: Build opentelemetry-java with tests
      if: ${{ env.patch_otel_java == 'true' && inputs.run_tests != 'false' }}
      build-root-directory: opentelemetry-java
      run: ./gradlew build publishToMavenLocal

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a #4.4.3
      
    - name: Build opentelemetry-java
      if: ${{ env.patch_otel_java == 'true' && inputs.run_tests == 'false' }}
      working-directory: opentelemetry-java
      run: ./gradlew publishToMavenLocal

    - name: cleanup opentelemetry-java
      run: rm -rf opentelemetry-java
      if: ${{ env.patch_otel_java == 'true' }}
      shell: bash

    - name: Build opentelemetry-java-contrib with tests
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a #4.4.3
    
    - name: Build opentelemetry-java-contrib without tests
      if: ${{ env.patch_otel_java_contrib == 'true' && inputs.run_tests != 'false' }}
      build-root-directory: opentelemetry-java-contrib
      run: ./gradlew build publishToMavenLocal

    - name: Build opentelemetry-java-contrib
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a #4.4.3

    - name: Build opentelemetry-java-contrib
      if: ${{ env.patch_otel_java_contrib == 'true' && inputs.run_tests == 'false' }}
      build-root-directory: opentelemetry-java-contrib
      run: ./gradlew publishToMavenLocal

    - name: cleanup opentelemetry-java-contrib
      run: rm -rf opentelemetry-java-contrib
      if: ${{ env.patch_otel_java_contrib == 'true' }}
      shell: bash
