name: "Patch dependencies"
description: |
  Patches direct dependencies of this project leveraging maven local to publish the results.

  This workflow will be noop if there is no dependency to patch, i.e.: no files in `.github/patchs`
  This workflow supports patching opentelemetry-java and opentelemetry-java-instrumentation repositories by executing
  the `patch.sh` script that will try to patch those repositories and after that will optionally test and then publish
  the artifacts to maven local.
  To add a patch you have to add a file in the `.github/patches/` directory with the name of the repository that must
  be patched.
  This action assumes that java was set correctly.
inputs:
  run_tests:
    default: "false"
    required: false
    description: "If the workflow should run tests of the dependencies. Anything different than false will evaluate to true"
  gpg_private_key:
    description: "The gpg key used to sign the artifacts"
    required: true
  gpg_password:
    description: "The gpg key password"
    required: true
runs:
  using: "composite"
  steps:
    - name: check patches
      run: |
        if [[ -f .github/patchs/opentelemetry-java.patch ]]; then
          echo 'patch_otel_java=true' >> $GITHUB_ENV
        fi
        if [[ -f .github/patchs/opentelemetry-java-instrumentation.patch ]]; then
            echo 'patch_otel_java_instrumentation=true' >> $GITHUB_ENV
        fi
        if [[ -f .github/patchs/opentelemetry-java-contrib.patch ]]; then
            echo 'patch_otel_java_contrib=true' >> $GITHUB_ENV
        fi
      shell: bash

    - name: Clone and patch repositories
      run: .github/scripts/patch.sh
      if: ${{ env.patch_otel_java == 'true' OR
              env.patch_otel_java_instrumentation == 'true' OR
              env.patch_otel_java_contrib == 'true' }}
      shell: bash

    - name: Build opentelemetry-java with tests
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java == 'true' && inputs.run_tests != 'false' }}
      with:
        arguments: build publishToMavenLocal
        build-root-directory: opentelemetry-java
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}

    - name: Build opentelemetry-java
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java == 'true' && inputs.run_tests == 'false' }}
      with:
        arguments: publishToMavenLocal
        build-root-directory: opentelemetry-java
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}

    - name: Build opentelemetry-java-contrib with tests
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java_contrib == 'true' && inputs.run_tests != 'false' }}
      with:
        arguments: build publishToMavenLocal
        build-root-directory: opentelemetry-java-contrib
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}

    - name: Build opentelemetry-java-contrib
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java_contrib == 'true' && inputs.run_tests == 'false' }}
      with:
        arguments: publishToMavenLocal
        build-root-directory: opentelemetry-java-contrib
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}

    - name: Build opentelemetry-java-instrumentation with tests
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java_instrumentation == 'true' && inputs.run_tests != 'false' }}
      with:
        arguments: check -x spotlessCheck publishToMavenLocal
        build-root-directory: opentelemetry-java-instrumentation
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}

    - name: Build opentelemetry java instrumentation
      uses: gradle/gradle-build-action@v2
      if: ${{ env.patch_otel_java_instrumentation == 'true' && inputs.run_tests == 'false' }}
      with:
        arguments: publishToMavenLocal
        build-root-directory: opentelemetry-java-instrumentation
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
        GPG_PASSWORD: ${{ inputs.gpg_password }}
