/*
 * Copyright Amazon.com, Inc. or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.opentelemetry.cloudwatch.spanmetrics;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.metrics.DoubleHistogram;
import io.opentelemetry.api.metrics.LongCounter;
import io.opentelemetry.api.metrics.Meter;
import io.opentelemetry.api.metrics.MeterProvider;
import io.opentelemetry.context.Context;
import io.opentelemetry.sdk.trace.ReadWriteSpan;
import io.opentelemetry.sdk.trace.ReadableSpan;
import io.opentelemetry.sdk.trace.SpanProcessor;
import io.opentelemetry.sdk.trace.data.SpanData;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import software.amazon.opentelemetry.cloudwatch.spanmetrics.internal.OpenTelemetryHolder;

/**
 * Generates request metrics from every recorded span, using the SpanMetricsConnector metric names
 * and dimensions. Paired with {@link AlwaysRecordSampler}, it sees 100% of spans regardless of the
 * trace sampling rate. It also stamps identity/dedup attributes (§6 of the spec) on each span at
 * start, so the backend can skip regenerating metrics from a span the extension already metered.
 */
public final class SpanMetricsProcessor implements SpanProcessor {

  private static final Logger logger = Logger.getLogger(SpanMetricsProcessor.class.getName());

  // Meter scope for the generated metrics. Must not contain the reserved "aws" token (CloudWatch
  // reserves "aws" in instrumentation scope names for its own vended metrics; verified empirically
  // that this name is accepted by the CloudWatch OTLP metrics endpoint). schema_url is
  // intentionally
  // not set — the schema version travels as the SCHEMA_VERSION attribute instead.
  private static final String SCOPE_NAME = "cloudwatch.plugin.otel.span_metrics";

  static final String SCHEMA_VERSION = "v1";

  // Resolved from the jar manifest's Implementation-Version (set by the build to project.version);
  // falls back to "unknown" when running outside a packaged jar (e.g. unit tests).
  static final String LIB_VERSION = resolveLibVersion();

  private static String resolveLibVersion() {
    String version = SpanMetricsProcessor.class.getPackage().getImplementationVersion();
    return version != null ? version : "unknown";
  }

  static final io.opentelemetry.api.common.AttributeKey<String> SCHEMA_ATTR =
      io.opentelemetry.api.common.AttributeKey.stringKey("aws.otel.span.metrics.schema");
  static final io.opentelemetry.api.common.AttributeKey<String> LIB_VERSION_ATTR =
      io.opentelemetry.api.common.AttributeKey.stringKey("aws.otel.extension.lib.version");

  private static final String CALLS_METRIC = "traces.span.metrics.calls";
  private static final String DURATION_METRIC = "traces.span.metrics.duration";

  // SpanMetricsConnector default boundaries expressed in seconds (spec §1).
  private static final List<Double> DURATION_BUCKETS_SECONDS =
      Arrays.asList(
          0.002, 0.004, 0.006, 0.008, 0.01, 0.05, 0.1, 0.2, 0.4, 0.8, 1.0, 1.4, 2.0, 5.0, 10.0,
          15.0);

  private static final double NANOS_PER_SECOND = 1_000_000_000.0;

  // The class of the API no-op meter, used to detect a MeterProvider with no metrics pipeline.
  private static final Class<? extends Meter> NOOP_METER_CLASS =
      MeterProvider.noop().get(SCOPE_NAME).getClass();

  // Initialized on the first onEnd() once the host has supplied a recording MeterProvider.
  private volatile LongCounter calls;
  private volatile DoubleHistogram duration;

  @Override
  public void onStart(Context parentContext, ReadWriteSpan span) {
    // Dedup + schema/lib markers: presence of the schema attribute tells the backend this span's
    // metrics were already generated by the extension (do not regenerate). Only stamp once we know
    // the host actually has a metrics pipeline that can deliver our metrics — otherwise the marker
    // would suppress backend generation for a metric the client never emits (see
    // ensureInstruments).
    // Guarded so a failure here can never propagate into the host application's span pipeline.
    try {
      if (!ensureInstruments()) {
        return;
      }
      span.setAttribute(SCHEMA_ATTR, SCHEMA_VERSION);
      span.setAttribute(LIB_VERSION_ATTR, LIB_VERSION);
    } catch (RuntimeException e) {
      logger.log(Level.WARNING, "Failed to stamp span metrics attributes", e);
    }
  }

  @Override
  public boolean isStartRequired() {
    return true;
  }

  @Override
  public void onEnd(ReadableSpan span) {
    try {
      if (!ensureInstruments()) {
        return;
      }
      // One toSpanData() snapshot per span: status and resource are only reachable via SpanData on
      // the ReadableSpan interface, so this allocation is inherent to the contract (reading fields
      // off the concrete SdkSpan would break non-SDK ReadableSpan implementations). Everything else
      // is read from this single snapshot.
      SpanData data = span.toSpanData();
      Attributes attributes = SpanMetricsAttributesBuilder.build(data);
      calls.add(1, attributes);
      long nanos = data.getEndEpochNanos() - data.getStartEpochNanos();
      duration.record(nanos / NANOS_PER_SECOND, attributes);
    } catch (RuntimeException e) {
      logger.log(Level.WARNING, "Failed to record span metrics", e);
    }
  }

  @Override
  public boolean isEndRequired() {
    return true;
  }

  private boolean ensureInstruments() {
    if (calls != null) {
      return true;
    }
    synchronized (this) {
      if (calls != null) {
        return true;
      }
      OpenTelemetry openTelemetry = OpenTelemetryHolder.get();
      if (openTelemetry == null) {
        return false;
      }
      Meter meter = openTelemetry.meterBuilder(SCOPE_NAME).build();
      // No metrics pipeline (e.g. OTEL_METRICS_EXPORTER=none or a reader-less MeterProvider): the
      // SDK hands back the API no-op meter. Recording would go nowhere, yet stamping the dedup
      // marker would still make the backend skip generation — so no side produces the metric. Stay
      // inert instead, so the backend generates from the sampled spans and the exactly-once
      // invariant
      // holds. Not cached: binding is late, so a real pipeline may appear on a later span.
      if (isNoopMeter(meter)) {
        return false;
      }
      duration =
          meter
              .histogramBuilder(DURATION_METRIC)
              .setUnit("s")
              .setExplicitBucketBoundariesAdvice(DURATION_BUCKETS_SECONDS)
              .build();
      // {call} is the UCUM annotation for counted things, matching OTel semconv counter
      // conventions (cf. {request}, {operation}). The collector spanmetrics connector leaves the
      // unit unset; the annotation is preferred because it states what is being counted.
      calls = meter.counterBuilder(CALLS_METRIC).setUnit("{call}").build();
    }
    return true;
  }

  // A reader-less SdkMeterProvider returns the API's no-op meter — the same class
  // MeterProvider.noop()
  // yields. Comparing against that stays correct across SDK versions (the concrete no-op class name
  // has changed between releases), unlike matching a hard-coded class name.
  private static boolean isNoopMeter(Meter meter) {
    return meter.getClass().equals(NOOP_METER_CLASS);
  }
}
