# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Inject Auto-Instrumentation Through Operator in EKS tests
on:
  pull_request:
    branches:
      - main
      - "release/v*"
        
env:
  TESTING_FRAMEWORK_REPO: aws-observability/aws-otel-test-framework
  DDB_TABLE_NAME: BatchTestCache
  NUM_BATCHES: 2
  TF_VAR_aoc_image_repo: public.ecr.aws/aws-observability/aws-otel-collector
  TF_VAR_operator_repository: 611364707713.dkr.ecr.us-west-2.amazonaws.com/adot-operator-staging

concurrency:
  group: operator-eks
  cancel-in-progress: false  

permissions:
  id-token: write
  contents: read

jobs:
  create-test-ref:
    runs-on: ubuntu-latest
    outputs:
      testRef: ${{ steps.setRef.outputs.ref }}
    steps:
      - name: Set testRef output
        id: setRef
        run: |
          if [[ ${{ github.ref_name }} == release/v* ]]; then 
            majorminor=$( echo ${{inputs.ADOTCollectorVersion }} | cut -f 1,2 -d .)
            echo "ref=release/${majorminor}.x" >> $GITHUB_OUTPUT
          else
            echo "ref=terraform" >> $GITHUB_OUTPUT
          fi

  get-testing-suites: 
    runs-on: ubuntu-latest
    needs: [create-test-ref]
    outputs:
      test-case-batch-key: ${{ steps.set-batches.outputs.batch-keys }}
      test-case-batch-value: ${{ steps.set-batches.outputs.batch-values }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TESTING_FRAMEWORK_REPO }}
          path: testing-framework
          ref: ${{ needs.create-test-ref.outputs.testRef }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: aws-otel-operator
          ref: ${{ inputs.ref }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18.9'
      - name: see env
        run: env
      - name: Create test batch key values
        id: set-batches
        run: |
          cd testing-framework/tools/batchTestGenerator
          go build
          ./batchTestGenerator github --testCaseFilePath=$GITHUB_WORKSPACE/aws-otel-operator/.github/workflows/testcases.json --maxBatch=${{ env.NUM_BATCHES }} \
            --include=EKS_ADOT_OPERATOR,EKS_ADOT_OPERATOR_ARM64
      - name: List testing suites
        run: |
          echo ${{ steps.set-batches.outputs.batch-keys }}
          echo ${{ steps.set-batches.outputs.batch-values }}

  run-batch-job:
    runs-on: ubuntu-latest
    needs: [get-testing-suites, create-test-ref]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-testing-suites.outputs.test-case-batch-key) }}

    steps:
        # required for versioning
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          path: aws-otel-operator

      - name: Set env vars for the job
        working-directory: aws-otel-operator
        run: |
          grep -v '\#' versions.txt | grep operator= | awk -F= '{print "OTELOPERATOR_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep opentelemetry-collector | awk -F= '{print "OTELCOL_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep targetallocator | awk -F= '{print "TARGETALLOCATOR_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep operator-opamp-bridge | awk -F= '{print "OPERATOR_OPAMP_BRIDGE_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep autoinstrumentation-java | awk -F= '{print "AUTO_INSTRUMENTATION_JAVA_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep autoinstrumentation-nodejs | awk -F= '{print "AUTO_INSTRUMENTATION_NODEJS_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep autoinstrumentation-python | awk -F= '{print "AUTO_INSTRUMENTATION_PYTHON_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep autoinstrumentation-dotnet | awk -F= '{print "AUTO_INSTRUMENTATION_DOTNET_VERSION="$2}' >> $GITHUB_ENV
          grep -v '\#' versions.txt | grep autoinstrumentation-apache-httpd | awk -F= '{print "AUTO_INSTRUMENTATION_APACHE_HTTPD_VERSION="$2}' >> $GITHUB_ENV
          echo "VERSION_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.1.0
        with:
          role-to-assume: ${{ secrets.OPERATOR_INTEG_TEST_ARN }}
          aws-region: us-west-2
          # 4 hours
          role-duration-seconds: 14400
      
      - name: Checkout testing framework
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TESTING_FRAMEWORK_REPO }}
          path: testing-framework
          ref: ${{ needs.create-test-ref.outputs.testRef }}

      - name: create test-case-batch file
        run: |
          jsonStr='${{ needs.get-testing-suites.outputs.test-case-batch-value }}'
          jsonStr="$(jq -r '.${{ matrix.BatchKey }} | join("\n")' <<< "${jsonStr}")"
          echo "$jsonStr" >> testing-framework/terraform/test-case-batch
          cat testing-framework/terraform/test-case-batch

      - name: Get TTL_DATE for cache
        id: date
        run: echo "ttldate=$(date -u -d "+7 days" +%s)" >> $GITHUB_OUTPUT

      - name: get Operator image tag
        id: operator_versioning
        working-directory: aws-otel-operator
        run: |
          shortsha="$(git rev-parse --short HEAD)"
          optag=${{ env.OTELOPERATOR_VERSION }}-$shortsha
          echo "operator-tag=$optag" >> $GITHUB_OUTPUT

      - name: run tests
        run: |
          export TTL_DATE=${{ steps.date.outputs.ttldate }}
          export TF_VAR_aoc_version=${{ github.event.inputs.ADOTCollectorVersion }}
          export TF_VAR_operator_tag=${{ steps.operator_versioning.outputs.operator-tag }}
          export DDB_BATCH_CACHE_SK=${{ steps.operator_versioning.outputs.operator-tag }}
          cd testing-framework/terraform
          make execute-batch-test
          
      - name: output cache misses
        if: ${{ failure() }}
        run: |
          export TF_VAR_aoc_version=${{ github.event.inputs.ADOTCollectorVersion }}
          export DDB_BATCH_CACHE_SK=${{ steps.operator_versioning.outputs.operator-tag }}
          cd testing-framework/terraform
          make checkCacheHits
      
      # This is here just in case workflow cancel
      # We first kill terraform processes to ensure that no state
      # file locks are being held from SIGTERMS dispatched in previous
      # steps. 
      - name: Destroy resources
        if: ${{ cancelled() }}
        shell: bash {0}
        run: |
          ps -ef | grep terraform | grep -v grep | awk '{print $2}' | xargs -n 1 kill
          cd testing-framework/terraform
          make terraformCleanup
