name: Migrate sonatype test
on:
  push:
    branches:
      - migrate-sonatype-test

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1

      - name: Publish patched dependencies to maven local
        uses: ./.github/actions/patch-dependencies
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_password: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build release with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build integrationTests -PlocalDocker=true -Prelease.version=0.0.1 --stacktrace

#      - name: Build and Publish release with Gradle
#        uses: gradle/gradle-build-action@v3
#        with:
#          arguments: build final closeAndReleaseSonatypeStagingRepository -Prelease.version=${{ github.event.inputs.version }} --stacktrace
#        env:
#          PUBLISH_TOKEN_USERNAME_TEST: ${{ secrets.PUBLISH_TOKEN_USERNAME_TEST }}
#          PUBLISH_TOKEN_PASSWORD_TEST: ${{ secrets.PUBLISH_TOKEN_PASSWORD_TEST }}
#          GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}